---
- name: This playboom install nginx
  hosts: NGINX
  become: no 
  remote_user: ubuntu
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest
    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes
    - name: DEploy the web Page
      copy:
        src:  ../vars/index.html
        dest: /var/www/html