# code: language=yaml
---
- name: Install apache
  apt:
    name: apache2
    state: present
- name: Start Apache
  service:
    name: httpd
    state: started
    enabled: yes
- name: DEploy the web Page to apache
  copy:
    src: ../vars/index.html
    dest: /var/www/html